version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2

  test:
    jobs:
      - test
